apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tradeops-secrets
  namespace: tradeops
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: tradeops-production-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: tradeops/production/postgresql
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: tradeops/production/jwt
        property: signingSecret
    - secretKey: IDENTITY_JWT_SECRET
      remoteRef:
        key: tradeops/production/jwt
        property: signingSecret
    - secretKey: IDENTITY_REFRESH_TOKEN_SECRET
      remoteRef:
        key: tradeops/production/jwt
        property: refreshSecret

